# Mockoon
@baseUrl = http://localhost:3020/v1
# Prism
# @baseUrl = http://localhost:4020

### Find all books
GET {{baseUrl}}/books
Authorization: Bearer TOKEN

### Find books by tag
GET {{baseUrl}}/books?tags=API
Authorization: Bearer TOKEN
